# Default values for testing-platform-backend.
image:
  repository: "ragaai/raga-llm-cpu-metrics"
  tag: "default"
  pullPolicy: IfNotPresent
imagePullSecrets:
  create: true
  name: "regcred"
fullnameOverride: "raga-llm-cpu-metrics-default"
serviceAccount:
  create: false
  name: "raga-role"
broker:
  create: false
  dlq: "event-failure-capture"
  retry: 3
trigger:
  create: false
service:
  port: 8080
resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 500m
    memory: 500Mi
autoscaling:
  minReplicas: 0
  maxReplicas: 3
  ScaleDownDelay: 2m
livenessProbe:
  httpGet:
    path: /api/healthcheck
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /api/healthcheck
    port: 8080
  initialDelaySeconds: 3
  periodSeconds: 3
containerConcurrency:
  enable: true
  limit: 1
  timeoutSeconds: 500
hpa:
  metric: memory
  target: 80
EnableTaints: true
nodeAffinity:
  key: architecture
  value: cpu
domainmapping:
  create: false
env:
  - name: AES_ENCRYPTION_KEY
    value: "c7e415394750cde6"
  - name: ENV_KEY_02
    value: "<env_val_02>"
  - name: ENV_KEY_03
    value: "<env_val_03>"
  - name: ENV_KEY_04
    value: "<env_val_04>"
  - name: ENV_KEY_05
    value: "<env_val_05>"
  - name: ENV_KEY_06
    value: "<env_val_06>"
  - name: ENV_KEY_07
    value: "<env_val_07>"
  - name: ENV_KEY_08
    value: "<env_val_08>"
  - name: ENV_KEY_09
    value: "<env_val_09>"
  - name: ENV_KEY_10
    value: "<env_val_10>"

