# Default values for testing-platform-backend.
image:
  repository: "ragaai/model-executor-release"
  tag: "20-1b81bee"
  pullPolicy: IfNotPresent
imagePullSecrets:
  create: true
  name: "regcred"
fullnameOverride: "model-executor"
serviceAccount:
  create: true
  name: "raga-role"
broker:
  create: true
  dlq: "event-failure-capture"
  retry: 1
trigger:
  create: true
service:
  port: 8090
  NodePort:
    create: false
    port: 32000
DisablePublicAccess: false
resources:
  limits:
    cpu: 500m
    memory: 500M
  requests:
    cpu: 100m
    memory: 200M
hpa:
  # metric availabe values memory | cpu
  metric: memory
  target: 80
autoscaling:
  minReplicas: 0
  maxReplicas: 3
  ScaleDownDelay: 15m
livenessProbe:
  httpGet:
    path: /api/healthcheck
    port: 8090
  initialDelaySeconds: 10
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /api/healthcheck
    port: 8090
  initialDelaySeconds: 3
  periodSeconds: 3
containerConcurrency:
  enable: true
  limit: 1
PVC:
  enable: false
  name: "model-executor-pvc"
  storageClassName: "standard"
env:
  # - name: AWS_ACCESS_KEY_ID
  #   valueFrom:
  #     secretKeyRef:
  #       name: aws-keys
  #       key: AWS_ACCESS_KEY_ID
  # - name: AWS_SECRET_ACCESS_KEY
  #   valueFrom:
  #     secretKeyRef:
  #       name: aws-keys
  #       key: AWS_SECRET_ACCESS_KEY
  - name: AWS_ACCESS_KEY_ID
    value: "Na"
  - name: AWS_SECRET_ACCESS_KEY
    value: "Na"

