# Default values for testing-platform-backend.
image:
  repository: "ragaai/knative-poc"
  tag: "cluster-operators-10"
  pullPolicy: IfNotPresent
imagePullSecrets:
  create: true
  name: "regcred"
fullnameOverride: "cluster-operators"
serviceAccount:
  create: true
  name: "raga-role"
broker:
  create: true
  dlq: "event-failure-capture"
  retry: 0
trigger:
  create: true
service:
  port: 5000
resources:
  limits:
    cpu: 1
    memory: 4500M
  requests:
    cpu: 1
    memory: 4500M
autoscaling:
  minReplicas: 0
  maxReplicas: 3
livenessProbe:
  httpGet:
    path: /api/healthcheck
    port: 5000
  initialDelaySeconds: 3
  periodSeconds: 3
readinessProbe:
  httpGet:
    path: /api/healthcheck
    port: 5000
  initialDelaySeconds: 3
  periodSeconds: 3
containerConcurrency:
  enable: true
  limit: 1
  timeoutSeconds: 1800
DeployOnARM: true
domainmapping:
  create: false
env:
  - name: ELASTIC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: cluster-operators
        key: ELASTIC_PASSWORD
  - name: S3_BUCKET
    valueFrom:
      secretKeyRef:
        name: cluster-operators
        key: S3_BUCKET
  - name: LM_EXECUTER_QUEUE
    value: "raga-dev-event-executor-input-queue.fifo"
  - name: LM_MAX_CONCURRENCY
    value: "20"
  - name: NUM_OF_CONCURRENT_PYTHON_OPERATORS_BATCH_PROCESSOR_LAMBDA
    value: "10"
  - name: PYTHON_OPERATORS_BATCH_PROCESSOR_QUEUE
    value: "raga-dev-python-operators-batch-processor-input-queue.fifo"
  - name: PYTHON_OPERATORS_BATCH_PROCESSOR_QUEUE_URL
    value: "https://sqs.us-east1.amazonaws.com/514856084243/raga-dev-python-operators-batch-processor-input-queue.fifo"
  - name: ELASTIC_URL
    value: "http://elastic-serch-cluster-es-http.elk.svc.cluster.local:9200"
  - name: NUMBA_CACHE_DIR
    value: "/tmp"
  - name: ELASTIC_USERNAME
    value: "elastic"
  - name: LM_EXECUTER_QUEUE
    value: "raga-dev-event-executor-input-queue.fifo"
  - name: SQS_ENDPOINT_URL
    value: "https://sqs.us-east1.amazonaws.com"
  - name: STATUS_UPDATER_QUEUE
    value: "raga-dev-status-updater-input-queue.fifo"
  - name: STATUS_UPDATER_QUEUE_URL
    value: "https://sqs.us-east1.amazonaws.com/514856084243/raga-dev-status-updater-input-queue.fifo"
  - name: STATUS_UPDATER_KAFKA_BROKER_URL
    value: "http://kafka-broker-ingress.knative-eventing.svc.cluster.local/raga/status-updater"
  - name: SERVICE_INVOCATION_METHOD
    value: "knative"
  - name: LM_EXECUTOR_KAFKA_BROKER_URL
    value: "http://kafka-broker-ingress.knative-eventing.svc.cluster.local/raga/event-executor"
  - name: PYTHON_OPERATOR_BATCH_PROCESSOR_KAFKA_BROKER_URL
    value: "http://kafka-broker-ingress.knative-eventing.svc.cluster.local/raga/python-operator-batch-processor"
  - name: LLM_OPERATOR
    value: "http://llm-operator.raga-models.svc.cluster.local"
  - name: FASTER_RCNN_MODEL_URL
    value: "http://faster-rcnn-model.raga-models.svc.cluster.local/"
  - name: REDIS_PORT
    value: "6379"
  - name: REDIS_URL
    value: "redis-master.redis.svc.cluster.local"
