# Default values for testing-platform-backend.
image:
  repository: "ragaai/data-loader-knative-release"
  tag: "7-6eb47b1"
  pullPolicy: IfNotPresent
metadata:
  name: "data-loader"
  labels:
    app: "data-loader"
imagePullSecrets:
  create: true
  name: "regcred"
fullnameOverride: "data-loader"

serviceAccount:
  create: true
  name: "raga-role"
  annotations: {}

broker:
  create: true
  dlq: "event-failure-capture"
  retry: 3

trigger:
  create: true

service:
  port: 8080

resources:
  limits:
    cpu: 1
    # memory: 640M
  requests:
    cpu: 100m
    memory: 640M

autoscaling:
  minReplicas: 0
  maxReplicas: 3

livenessProbe:
  httpGet:
    path: /api/healthcheck
    port: 8080
  initialDelaySeconds: 3
  periodSeconds: 3
readinessProbe:
  httpGet:
    path: /api/healthcheck
    port: 8080
  initialDelaySeconds: 3
  periodSeconds: 3

domainmapping:
  create: false
  domain: NA
  service: NA

containerConcurrency:
  enable: true
  limit: 3

env:
  - name: REDIS_PORT
    value: '6379'
  - name: REDIS_URL
    value: 'redis-master.redis.svc.cluster.local'