# Default values for testing-platform-backend.
image:
  repository: "ragaai/knative-poc"
  tag: "event-executor4"
  pullPolicy: IfNotPresent
imagePullSecrets:
  create: true
  name: "regcred"
fullnameOverride: "event-executor"
serviceAccount:
  create: true
  name: "raga-role"
broker:
  create: true
  dlq: "event-failure-capture"
  retry: 3
trigger:
  create: true
service:
  port: 8000
resources:
  limits:
    cpu: 1
    memory: 2500M
  requests:
    cpu: 100m
    memory: 640M
autoscaling:
  minReplicas: 0
  maxReplicas: 3
livenessProbe:
  httpGet:
    path: /api/healthcheck
    port: 8000
  initialDelaySeconds: 3
  periodSeconds: 3
readinessProbe:
  httpGet:
    path: /api/healthcheck
    port: 8000
  initialDelaySeconds: 3
  periodSeconds: 3
containerConcurrency:
  enable: false
  limit: 1
DeployOnARM: false
domainmapping:
  create: false
env:
  - name: REDIS_PORT
    value: "6379"
  - name: REDIS_URL
    value: "redis-master.redis.svc.cluster.local"
  - name: SERVICE_INVOCATION_METHOD
    value: "knative"
  - name: DATA_LOADER_KAFKA_BROKER_URL
    value: "http://kafka-broker-ingress.knative-eventing.svc.cluster.local/raga/data-loader"
  - name: STATUS_UPDATER_KAFKA_BROKER_URL
    value: "http://kafka-broker-ingress.knative-eventing.svc.cluster.local/raga/status-updater"