# Default values for testing-platform-backend.
image:
  repository: "ragaai/plotly-knative-release"
  tag: "4-e762717"
  pullPolicy: IfNotPresent

imagePullSecrets:
  create: true
  name: "regcred"
fullnameOverride: "plotly"

serviceAccount:
  create: false
  name: "raga-role"
  annotations: {}

broker:
  create: false
  dlq: "event-failure-capture"
  retry: 3

trigger:
  create: false

service:
  port: 8050

resources: 
  limits:
    cpu: 1
    memory: 3500M
  requests:
    cpu: 100m
    memory: 640M

autoscaling:
  minReplicas: 0
  maxReplicas: 3

livenessProbe:
  httpGet:
    path: /plotly/api/health
    port: 8050
  initialDelaySeconds: 10
  periodSeconds: 3
readinessProbe:
  httpGet:
    path: /plotly/api/health
    port: 8050
  initialDelaySeconds: 3
  periodSeconds: 3

domainmapping:
  create: false
  domain: NA
  service: NA

containerConcurrency:
  enable: true
  limit: 1

env:
  - name: JWT_SECRET
    valueFrom:
      secretKeyRef:
        name: plotly
        key: JWT_SECRET
  - name: API_URL
    value: "http://esservice.raga.svc.cluster.local"
  - name: CACHE_TIMEOUT
    value: "10800"
  - name: NUMBA_CACHE_DIR
    value: "/tmp"
  - name: REDIS_URL
    value: "redis://redis-master.redis.svc.cluster.local:6379"
  - name: TF_API_URL
    value: "http://backend.raga.svc.cluster.local"