# Default values for testing-platform-backend.
image:
  repository: "ragaai/property-manager-client-knative-release"
  tag: "4-972040c"
  pullPolicy: IfNotPresent

imagePullSecrets:
  create: true
  name: "regcred"
fullnameOverride: "property-manager-client"

serviceAccount:
  create: true
  name: "property-manager-client"

broker:
  create: true
  dlq: "event-failure-capture"
  retry: 3

trigger:
  create: true

service:
  port: 6000

resources: 
  limits:
    cpu: 100m
    memory: 640M
  requests:
    cpu: 100m
    memory: 640M

autoscaling:
  minReplicas: 0
  maxReplicas: 1

livenessProbe:
  httpGet:
    path: /api/healthcheck
    port: 6000
  initialDelaySeconds: 3
  periodSeconds: 3
readinessProbe:
  httpGet:
    path: /api/healthcheck
    port: 6000
  initialDelaySeconds: 3
  periodSeconds: 3

containerConcurrency:
  enable: true
  limit: 3

env:
  - name: REDIS_HOST
    valueFrom: 
      secretKeyRef:
        name: property-manager-client
        key: REDIS_HOST
  - name: REDIS_PORT
    valueFrom: 
      secretKeyRef:
        name: property-manager-client
        key: REDIS_PORT