# Default values for testing-platform-backend.
image:
  repository: "ragaai/python-operator-knative-release"
  tag: "5-0873c72"
  pullPolicy: IfNotPresent

imagePullSecrets:
  create: true
  name: "regcred"
fullnameOverride: "python-operator"

serviceAccount:
  create: true
  name: "raga-role"
  annotations: {}

broker:
  create: true
  dlq: "event-failure-capture"
  retry: 0

trigger:
  create: true

service:
  port: 5000

resources: 
  limits:
    cpu: 1
    memory: 4500M
  requests:
    cpu: 1
    memory: 4500M

autoscaling:
  minReplicas: 1
  maxReplicas: 3

livenessProbe:
  httpGet:
    path: /api/healthcheck
    port: 5000
  initialDelaySeconds: 3
  periodSeconds: 3
readinessProbe:
  httpGet:
    path: /api/healthcheck
    port: 5000
  initialDelaySeconds: 3
  periodSeconds: 3

domainmapping:
  create: false
  domain: NA
  service: NA

containerConcurrency:
  enable: true
  limit: 1
  timeoutSeconds: 1800
env:
  - name: REDIS_PORT
    value: '6379'
  - name: REDIS_URL
    value: 'redis-master.redis.svc.cluster.local'