# Default values for testing-platform-backend.
image:
  repository: "ragaai/python-operator-batch-processor-knative-release"
  tag: "4-9141e9d"
  pullPolicy: IfNotPresent

imagePullSecrets:
  create: true
  name: "regcred"
fullnameOverride: "python-operator-batch-processor"

DisablePublicAccess: true

serviceAccount:
  create: true
  name: "raga-role"
  annotations: {}

broker:
  create: true
  dlq: "event-failure-capture"
  retry: 3

trigger:
  create: true

service:
  port: 8000

resources: 
  limits:
    cpu: 1
    memory: 2500M
  requests:
    cpu: 100m
    memory: 640M

autoscaling:
  minReplicas: 0
  maxReplicas: 3

livenessProbe:
  httpGet:
    path: /api/healthcheck
    port: 8000
  initialDelaySeconds: 3
  periodSeconds: 3
readinessProbe:
  httpGet:
    path: /api/healthcheck
    port: 8000
  initialDelaySeconds: 3
  periodSeconds: 3

domainmapping:
  create: false
  domain: NA
  service: NA

containerConcurrency:
  enable: true
  limit: 3

env:
  - name: ELASTIC_PASSWORD
    valueFrom: 
      secretKeyRef:
        name: python-operator-batch-processor
        key: ELASTIC_PASSWORD
  - name: ELASTIC_URL
    valueFrom: 
      secretKeyRef:
        name: python-operator-batch-processor
        key: ELASTIC_URL
  - name: S3_BUCKET
    valueFrom: 
      secretKeyRef:
        name: python-operator-batch-processor
        key: S3_BUCKET
  - name: LM_EXECUTER_QUEUE
    value: "NA as it is a Knative environment"
  - name: LM_MAX_CONCURRENCY
    value: 20
  - name: SQS_ENDPOINT_URL
    value: "NA as it is a Knative environment"
  - name: NUMBA_CACHE_DIR
    value: "/tmp"
  - name: STATUS_UPDATER_QUEUE
    value: "NA as it is a Knative environment"
  - name: STATUS_UPDATER_QUEUE_URL
    value: "NA as it is a Knative environment"
  # - name: SERVICE_INVOCATION_METHOD
  #   valueFrom: 
  #     secretKeyRef:
  #       name: python-operator-batch-processor
  #       key: SERVICE_INVOCATION_METHOD