# Default values for testing-platform-backend.
image:
  repository: "ragaai/umap-operators-knative-release"
  tag: "7-161a484"
  pullPolicy: IfNotPresent

imagePullSecrets:
  create: true
  name: "regcred"
fullnameOverride: "umap-operators"

serviceAccount:
  create: true
  name: "umap-operators"

broker:
  create: true
  dlq: "event-failure-capture"
  retry: 0

trigger:
  create: true

service:
  port: 5000

resources: 
  limits:
    cpu: 1
    memory: 4500M
  requests:
    cpu: 1
    memory: 4500M

autoscaling:
  minReplicas: 1
  maxReplicas: 3

livenessProbe:
  httpGet:
    path: /api/healthcheck
    port: 5000
  initialDelaySeconds: 3
  periodSeconds: 3
readinessProbe:
  httpGet:
    path: /api/healthcheck
    port: 5000
  initialDelaySeconds: 3
  periodSeconds: 3


containerConcurrency:
  enable: true
  limit: 1
  timeoutSeconds: 1800
env:
  - name: ELASTIC_PASSWORD
    valueFrom: 
      secretKeyRef:
        name: umap-operators
        key: ELASTIC_PASSWORD
  - name: LM_EXECUTER_QUEUE
    valueFrom: 
      secretKeyRef:
        name: umap-operators
        key: LM_EXECUTER_QUEUE
  - name: LM_MAX_CONCURRENCY
    valueFrom: 
      secretKeyRef:
        name: umap-operators
        key: LM_MAX_CONCURRENCY
  - name: NUM_OF_CONCURRENT_PYTHON_OPERATORS_BATCH_PROCESSOR_LAMBDA
    valueFrom: 
      secretKeyRef:
        name: umap-operators
        key: NUM_OF_CONCURRENT_PYTHON_OPERATORS_BATCH_PROCESSOR_LAMBDA
  - name: PYTHON_OPERATORS_BATCH_PROCESSOR_QUEUE
    valueFrom: 
      secretKeyRef:
        name: umap-operators
        key: PYTHON_OPERATORS_BATCH_PROCESSOR_QUEUE
  - name: PYTHON_OPERATORS_BATCH_PROCESSOR_QUEUE_URL
    valueFrom: 
      secretKeyRef:
        name: umap-operators
        key: PYTHON_OPERATORS_BATCH_PROCESSOR_QUEUE_URL
  - name: ELASTIC_URL
    valueFrom:
      secretKeyRef:
        name: umap-operators
        key: ELASTIC_URL
  - name: NUMBA_CACHE_DIR
    valueFrom:
      secretKeyRef:
        name: umap-operators
        key: NUMBA_CACHE_DIR
  - name: ELASTIC_USERNAME
    valueFrom:
      secretKeyRef:
        name: umap-operators
        key: ELASTIC_USERNAME
  - name: LM_EXECUTER_QUEUE
    valueFrom:
      secretKeyRef:
        name: umap-operators
        key: LM_EXECUTER_QUEUE
  - name: S3_BUCKET
    valueFrom:
      secretKeyRef:
        name: umap-operators
        key: S3_BUCKET
  - name: SQS_ENDPOINT_URL
    valueFrom:
      secretKeyRef:
        name: umap-operators
        key: SQS_ENDPOINT_URL
  - name: STATUS_UPDATER_QUEUE
    valueFrom:
      secretKeyRef:
        name: umap-operators
        key: STATUS_UPDATER_QUEUE
  - name: STATUS_UPDATER_QUEUE_URL
    valueFrom:
      secretKeyRef:
        name: umap-operators
        key: STATUS_UPDATER_QUEUE_URL
  - name: STATUS_UPDATER_KAFKA_BROKER_URL
    valueFrom:
      secretKeyRef:
        name: umap-operators
        key: STATUS_UPDATER_KAFKA_BROKER_URL
  - name: SERVICE_INVOCATION_METHOD
    valueFrom:
      secretKeyRef:
        name: umap-operators
        key: SERVICE_INVOCATION_METHOD
  - name: LM_EXECUTOR_KAFKA_BROKER_URL
    valueFrom:
      secretKeyRef:
        name: umap-operators
        key: LM_EXECUTOR_KAFKA_BROKER_URL
  - name: PYTHON_OPERATOR_BATCH_PROCESSOR_KAFKA_BROKER_URL
    valueFrom: 
      secretKeyRef:
        name: umap-operators
        key: PYTHON_OPERATOR_BATCH_PROCESSOR_KAFKA_BROKER_URL
  - name: LLM_OPERATOR
    valueFrom:
      secretKeyRef:
        name: umap-operators
        key: LLM_OPERATOR
  - name: FASTER_RCNN_MODEL_URL
    valueFrom:
      secretKeyRef:
        name: umap-operators
        key: FASTER_RCNN_MODEL_URL
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: backend
        key: AWS_ACCESS_KEY_ID
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: backend
        key: AWS_SECRET_ACCESS_KEY
  - name: LLM_OPERATOR
    valueFrom:
      secretKeyRef:
        name: umap-operators
        key: LLM_OPERATOR
  - name: FASTER_RCNN_MODEL_URL
    valueFrom:
      secretKeyRef:
        name: umap-operators
        key: FASTER_RCNN_MODEL_URL
