# Default values for testing-platform-backend.
image:
  repository: "ragaai/umap-operators-knative-release"
  tag: "7-161a484"
  pullPolicy: IfNotPresent

imagePullSecrets:
  create: true
  name: "regcred"
fullnameOverride: "umap-operators"

serviceAccount:
  create: true
  name: "raga-role"
  annotations: {}

broker:
  create: true
  dlq: "event-failure-capture"
  retry: 0

trigger:
  create: true

service:
  port: 5000

resources: 
  limits:
    cpu: 1
    memory: 4500M
  requests:
    cpu: 1
    memory: 4500M

autoscaling:
  minReplicas: 1
  maxReplicas: 3

livenessProbe:
  httpGet:
    path: /api/healthcheck
    port: 5000
  initialDelaySeconds: 3
  periodSeconds: 3
readinessProbe:
  httpGet:
    path: /api/healthcheck
    port: 5000
  initialDelaySeconds: 3
  periodSeconds: 3

domainmapping:
  create: false
  domain: NA
  service: NA

containerConcurrency:
  enable: true
  limit: 1
  timeoutSeconds: 1800
env:
  - name: ELASTIC_PASSWORD
    valueFrom: 
      secretKeyRef:
        name: umap-operators
        key: ELASTIC_PASSWORD
  - name: ELASTIC_URL
    valueFrom:
      secretKeyRef:
        name: umap-operators
        key: ELASTIC_URL
  - name: ELASTIC_USERNAME
    valueFrom:
      secretKeyRef:
        name: umap-operators
        key: ELASTIC_USERNAME
  - name: S3_BUCKET
    valueFrom:
      secretKeyRef:
        name: umap-operators
        key: S3_BUCKET
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: backend
        key: AWS_ACCESS_KEY_ID
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: backend
        key: AWS_SECRET_ACCESS_KEY
  - name: LM_EXECUTER_QUEUE
    value: "NA as it is a Knative environment"
  - name: LM_MAX_CONCURRENCY
    value: 20
  - name: NUM_OF_CONCURRENT_PYTHON_OPERATORS_BATCH_PROCESSOR_LAMBDA
    value: 10
  - name: PYTHON_OPERATORS_BATCH_PROCESSOR_QUEUE
    value: "NA as it is a Knative environment"
  - name: PYTHON_OPERATORS_BATCH_PROCESSOR_QUEUE_URL
    value: "NA as it is a Knative environment"
  - name: NUMBA_CACHE_DIR
    value: "/tmp"
  - name: LM_EXECUTER_QUEUE
    value: "NA as it is a Knative environment"
  - name: SQS_ENDPOINT_URL
    value: "https://sqs.ap-south-1.amazonaws.com"
  - name: STATUS_UPDATER_QUEUE
    value: "NA as it is a Knative environment"
  - name: STATUS_UPDATER_QUEUE_URL
    value: "NA as it is a Knative environment"
  - name: STATUS_UPDATER_KAFKA_BROKER_URL
    value: "http://kafka-broker-ingress.knative-eventing.svc.cluster.local/raga/status-updater"
  - name: SERVICE_INVOCATION_METHOD
    value: "knative"
  - name: LM_EXECUTOR_KAFKA_BROKER_URL
    value: "http://kafka-broker-ingress.knative-eventing.svc.cluster.local/raga/event-executor"
  - name: PYTHON_OPERATOR_BATCH_PROCESSOR_KAFKA_BROKER_URL
    value: "http://kafka-broker-ingress.knative-eventing.svc.cluster.local/raga/python-operator-batch-processor"
  - name: LLM_OPERATOR
    value: "http://llm-operator.raga-models.svc.cluster.local"
  - name: FASTER_RCNN_MODEL_URL
    value: "http://faster-rcnn-model.raga-models.svc.cluster.local/"

