# Default values for testing-platform-backend.
image:
  repository: "ragaai/lightweight-poc"
  tag: "event-executor1"
  pullPolicy: IfNotPresent
imagePullSecrets:
  create: true
  name: "regcred"
fullnameOverride: "event-executor"
serviceAccount:
  create: true
  name: "raga-role"
broker:
  create: true
  dlq: "event-failure-capture"
  retry: 3
trigger:
  create: true
service:
  port: 8000
  NodePort:
    create: false
    port: 31000
resources:
  limits:
    cpu: 500m
    memory: 500M
  requests:
    cpu: 500m
    memory: 500M
autoscaling:
  minReplicas: 0
  maxReplicas: 3
livenessProbe:
  httpGet:
    path: /api/healthcheck
    port: 8000
  initialDelaySeconds: 3
  periodSeconds: 3
readinessProbe:
  httpGet:
    path: /api/healthcheck
    port: 8000
  initialDelaySeconds: 3
  periodSeconds: 3
containerConcurrency:
  enable: false
  limit: 1
DeployOnARM: false
domainmapping:
  create: false
env:
  - name: REDIS_PORT
    value: "6379"
  - name: REDIS_URL
    value: "redis-master.redis.svc.cluster.local"
  - name: SERVICE_INVOCATION_METHOD
    value: "knative"
  - name: DATA_LOADER_KAFKA_BROKER_URL
    value: "http://data-loader.raga.svc.cluster.local"
  - name: STATUS_UPDATER_KAFKA_BROKER_URL
    value: "http://status-updater.raga.svc.cluster.local"
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: aws-keys
        key: AWS_ACCESS_KEY_ID
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: aws-keys
        key: AWS_SECRET_ACCESS_KEY