# Default values for testing-platform-backend.
image:
  repository: "ragaai/lightweight-poc"
  tag: "frontend-5"
  pullPolicy: IfNotPresent
imagePullSecrets:
  create: true
  name: "regcred"
fullnameOverride: "frontend"
serviceAccount:
  create: true
  name: "raga-role"
broker:
  create: false
  dlq: "event-failure-capture"
  retry: 3
trigger:
  create: false
service:
  port: 80
  NodePort:
    create: true
    port: 31000
resources:
  limits:
    cpu: 500m
    memory: 500M
  requests:
    cpu: 100m
    memory: 200M
autoscaling:
  minReplicas: 1
  maxReplicas: 3
livenessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 10
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 10
  periodSeconds: 3
containerConcurrency:
  enable: false
  limit: 1
DeployOnARM: false
domainmapping:
  create: true
  domain: dev4.ragaai.ai
  service: frontend
# env:
#   - name: ELASTIC_SEARCH_BASE_URL
#     valueFrom: 
#       secretKeyRef:
#         name: frontend
#         key: ELASTIC_SEARCH_BASE_URL
