# Default values for testing-platform-api.
image:
  repository: "ragaai/lightweight-poc"
  tag: "llm-platform-api1"
  pullPolicy: IfNotPresent
imagePullSecrets:
  create: true
  name: "regcred"
fullnameOverride: "llm-platform-api"
serviceAccount:
  create: true
  name: "raga-role"
broker:
  create: false
  dlq: "event-failure-capture"
  retry: 3
trigger:
  create: false
service:
  port: 8080
  NodePort:
    create: true
    port: 31000
resources:
  limits:
    cpu: 1
    memory: 1024M
  requests:
    cpu: 1
    memory: 1024M
autoscaling:
  minReplicas: 1
  maxReplicas: 3
livenessProbe:
  httpGet:
    path: /api/healthcheck
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /api/healthcheck
    port: 8080
  initialDelaySeconds: 3
  periodSeconds: 3
containerConcurrency:
  enable: false
  limit: 1
DeployOnARM: false
domainmapping:
  create: true
  domain: llm-platform.dev4.ragaai.ai
  service: llm-platform-api
env:
  - name: API_HOST
    valueFrom:
      secretKeyRef:
        name: llm-platform-api
        key: API_HOST
  - name: AWS_BUCKET_NAME
    valueFrom:
      secretKeyRef:
        name: llm-platform-api
        key: AWS_BUCKET_NAME
  - name: FRONTEND_URL
    valueFrom:
      secretKeyRef:
        name: llm-platform-api
        key: FRONTEND_URL
  - name: GITHUB_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: llm-platform-api
        key: GITHUB_CLIENT_ID
  - name: GITHUB_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: llm-platform-api
        key: GITHUB_CLIENT_SECRET
  - name: GOOGLE_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: llm-platform-api
        key: GOOGLE_CLIENT_ID
  - name: GOOGLE_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: llm-platform-api
        key: GOOGLE_CLIENT_SECRET
  - name: JWT_SECRET
    valueFrom:
      secretKeyRef:
        name: llm-platform-api
        key: JWT_SECRET
  - name: MYSQL_PASSWORD
    valueFrom:
      secretKeyRef:
        name: llm-platform-api
        key: MYSQL_PASSWORD
  - name: MYSQL_URL
    valueFrom:
      secretKeyRef:
        name: llm-platform-api
        key: MYSQL_URL
  - name: MYSQL_USERNAME
    valueFrom:
      secretKeyRef:
        name: llm-platform-api
        key: MYSQL_USERNAME
  - name: AWS_REGION
    valueFrom:
      secretKeyRef:
        name: llm-platform-api
        key: AWS_REGION
  # - name: AWS_ACCESS_KEY_ID
  #   valueFrom:
  #     secretKeyRef:
  #       name: backend
  #       key: AWS_ACCESS_KEY_ID
  # - name: AWS_SECRET_ACCESS_KEY
  #   valueFrom:
  #     secretKeyRef:
  #       name: backend
  #       key: AWS_SECRET_ACCESS_KEY
  - name: RAG_SUGGESTION_URL
    value: 'dummy value to skip error in knative'
  - name: FLOWISE_URL
    value: 'dummy value to skip error in knative'
  - name: UAM_JWT_TOKEN_EXPIRATION
    value: '86400000'
  - name: DATA_LOADER_ARN
    value: 'NA as it is a Knative environment'
  - name: DATA_LOADER_SQS_QUEUE_URL
    value: 'NA as it is a Knative environment'
  - name: DEFAULT_DATA_LOADER_ARN
    value: 'NA as it is a Knative environment'
  - name: ES_URL
    value: 'http://llm-platform-esservice.raga.svc.cluster.local'
  - name: OOD_ARN
    value: 'NA as it is a Knative environment'
  - name: PYTHON_OPERATOR_ARN
    value: 'NA as it is a Knative environment'
  - name: PYTHON_OPERATOR_SQS_QUEUE_URL
    value: 'NA as it is a Knative environment'
  - name: DATA_LOADER_KAFKA_BROKER_URL
    value: 'http://data-loader.raga.svc.cluster.local'
  - name: PYTHON_OPERATOR_KAFKA_BROKER_URL
    value: 'http://llm-platform-operators.raga.svc.cluster.local'
  - name: SERVICE_INVOCATION_METHOD
    value: 'knative'
  - name: MAX_FILE_SIZE_IN_GB
    value: '5'
  - name: STATUS_UPDATER_KAFKA_BROKER_URL
    value: 'http://status-updater.raga.svc.cluster.local'
  - name: PROPERTY_MANAGER_SERVICE_URL
    value: 'http://property-manager-client.raga.svc.cluster.local'
  - name: REDIS_URL
    value: 'redis-master.redis.svc.cluster.local'
  - name: REDIS_PORT
    value: '6379'
  - name: PROPERTY_MANAGER_LOADER_URL
    value: 'http://property-manager-client.raga.svc.cluster.local'
  - name: CLOUD_ENVIRONMENT
    value: 'AWS'
  - name: AZURE_CONNECTION_STRING
    value: 'Azure'
  - name: JWT_TOKEN_EXPIRATION
    value: '86400000'
  - name: LOGGING_LEVEL
    value: 'INFO'
  - name: JWT_REFRESH_TOKEN_EXPIRATION
    value: '86400000'
