# Default values for testing-platform-backend.
image:
  repository: "ragaai/lightweight-poc"
  tag: "llm-platform-status-updater-2"
  pullPolicy: IfNotPresent
imagePullSecrets:
  create: true
  name: "regcred"
fullnameOverride: "llm-platform-status-updater"
serviceAccount:
  create: true
  name: "raga-role"
broker:
  create: true
  dlq: "event-failure-capture"
  retry: 3
trigger:
  create: true
service:
  port: 6000
  NodePort:
    create: false
    port: 31200
resources:
  limits:
    cpu: 100m
    memory: 640M
  requests:
    cpu: 100m
    memory: 640M
autoscaling:
  minReplicas: 1
  maxReplicas: 3
livenessProbe:
  httpGet:
    path: /api/healthcheck
    port: 6000
  initialDelaySeconds: 3
  periodSeconds: 3
readinessProbe:
  httpGet:
    path: /api/healthcheck
    port: 6000
  initialDelaySeconds: 3
  periodSeconds: 3
containerConcurrency:
  enable: true
  limit: 1
DeployOnARM: true
domainmapping:
  create: false
env:
  - name: REDIS_PORT
    value: "6379"
  - name: REDIS_URL
    value: "redis-master.redis.svc.cluster.local"
  - name: SERVICE_INVOCATION_METHOD
    value: "knative"
  - name: PYTHON_OPERATOR_KAFKA_BROKER_URL
    value: "http://llm-platform-operators.raga.svc.cluster.local"
  - name: DATA_LOADER_KAFKA_BROKER_URL
    value: "http://data-loader.raga.svc.cluster.local"
  - name: UMAP_OPERATOR_KAFKA_BROKER_URL
    value: "http://umap-operators.raga.svc.cluster.local"
  - name: MODEL_PACKAGER_KAFKA_BROKER_URL
    value: "http://model-packager.raga-models.svc.cluster.local"
  - name: LLM_DATA_LOADER_KAFKA_BROKER_URL
    value: "http://llm-data-loader.raga.svc.cluster.local"
  - name: PREFIX
    value: "llm-platform"
