# Default values for testing-platform-backend.
image:
  repository: "ragaai/ragaai/lightweight-poc"
  tag: "python-operator-1"
  pullPolicy: IfNotPresent
imagePullSecrets:
  create: true
  name: "regcred"
fullnameOverride: "python-operator"
serviceAccount:
  create: true
  name: "raga-role"
broker:
  create: true
  dlq: "event-failure-capture"
  retry: 0
trigger:
  create: true
service:
  port: 5000
  NodePort:
    create: false
    port: 31000
resources:
  limits:
    cpu: 1
    memory: 2048M
  requests:
    cpu: 1
    memory: 2048M
autoscaling:
  minReplicas: 0
  maxReplicas: 3
livenessProbe:
  httpGet:
    path: /api/healthcheck
    port: 5000
  initialDelaySeconds: 3
  periodSeconds: 3
readinessProbe:
  httpGet:
    path: /api/healthcheck
    port: 5000
  initialDelaySeconds: 3
  periodSeconds: 3
containerConcurrency:
  enable: true
  limit: 1
  timeoutSeconds: 1800
DeployOnARM: true
domainmapping:
  create: false
env:
  - name: REDIS_PORT
    value: "6379"
  - name: REDIS_URL
    value: "redis-master.redis.svc.cluster.local"
  - name: SERVICE_INVOCATION_METHOD
    value: "knative"
  - name: STATUS_UPDATER_KAFKA_BROKER_URL
    value: "http://status-updater.raga.svc.cluster.local"
  - name: LM_EXECUTOR_KAFKA_BROKER_URL
    value: "http://event-executor.raga.svc.cluster.local"
  - name: PYTHON_OPERATOR_BATCH_PROCESSOR_KAFKA_BROKER_URL
    value: "http://python-operator-batch-processor.raga.svc.cluster.local"
  - name: FASTER_RCNN_MODEL_URL
    value: "http://faster-rcnn-model.raga-models.svc.cluster.local/"
  - name: LLM_OPERATOR
    value: "http://llm-operator.raga-models.svc.cluster.local"
  - name: FASTER_RCNN_MODEL_URL
    value: "http://faster-rcnn-model.raga-models.svc.cluster.local/"
