# Default values for testing-platform-backend.
image:
  repository: "ragaai/knative-poc"
  tag: "python-operator-batch-processor4"
  pullPolicy: IfNotPresent
imagePullSecrets:
  create: true
  name: "regcred"
fullnameOverride: "python-operator-batch-processor"
DisablePublicAccess: true
serviceAccount:
  create: true
  name: "raga-role"
broker:
  create: true
  dlq: "event-failure-capture"
  retry: 3
trigger:
  create: true
service:
  port: 8000
  NodePort:
    create: false
    port: 31000
resources:
  limits:
    cpu: 500m
    memory: 500M
  requests:
    cpu: 500m
    memory: 500M
autoscaling:
  minReplicas: 0
  maxReplicas: 3
livenessProbe:
  httpGet:
    path: /api/healthcheck
    port: 8000
  initialDelaySeconds: 3
  periodSeconds: 3
readinessProbe:
  httpGet:
    path: /api/healthcheck
    port: 8000
  initialDelaySeconds: 3
  periodSeconds: 3
containerConcurrency:
  enable: true
  limit: 1
DeployOnARM: true
domainmapping:
  create: false
env:
  - name: REDIS_PORT
    value: "6379"
  - name: REDIS_URL
    value: "redis-master.redis.svc.cluster.local"
  - name: SERVICE_INVOCATION_METHOD
    value: "knative"
  - name: LM_EXECUTER_QUEUE
    value: "NA"
  - name: NUMBA_CACHE_DIR
    value: "/tmp"
