# Default values for testing-platform-backend.
image:
  repository: "ragaai/lightweight-poc"
  tag: "umap-operators-1"
  pullPolicy: IfNotPresent
imagePullSecrets:
  create: true
  name: "regcred"
fullnameOverride: "umap-operators"
serviceAccount:
  create: true
  name: "raga-role"
broker:
  create: true
  dlq: "event-failure-capture"
  retry: 0
trigger:
  create: true
service:
  port: 9000
  NodePort:
    create: false
    port: 31000
DisablePublicAccess: true
resources:
  limits:
    cpu: 500m
    memory: 500M
  requests:
    cpu: 100m
    memory: 200M
autoscaling:
  minReplicas: 0
  maxReplicas: 3
  ScaleDownDelay: 1m
livenessProbe:
  httpGet:
    path: /api/healthcheck
    port: 9000
  initialDelaySeconds: 3
  periodSeconds: 3
readinessProbe:
  httpGet:
    path: /api/healthcheck
    port: 9000
  initialDelaySeconds: 3
  periodSeconds: 3
containerConcurrency:
  enable: true
  limit: 1
  timeoutSeconds: 1800
DeployOnARM: true
domainmapping:
  create: false
env:
  - name: REDIS_PORT
    value: "6379"
  - name: REDIS_URL
    value: "redis-master.redis.svc.cluster.local"
  - name: SERVICE_INVOCATION_METHOD
    value: "knative"
  - name: LM_EXECUTER_QUEUE
    value: "NA"
  - name: LM_MAX_CONCURRENCY
    value: "knative"
  - name: NUM_OF_CONCURRENT_PYTHON_OPERATORS_BATCH_PROCESSOR_LAMBDA
    value: "20"
  - name: PYTHON_OPERATORS_BATCH_PROCESSOR_QUEUE
    value: "NA"
  - name: PYTHON_OPERATORS_BATCH_PROCESSOR_QUEUE_URL
    value: "NA"
  - name: S3_BUCKET
    value: "NA"
  - name: STATUS_UPDATER_KAFKA_BROKER_URL
    value: "http://status-updater.raga.svc.cluster.local"
  - name: LM_EXECUTOR_KAFKA_BROKER_URL
    value: "http://event-executor.raga.svc.cluster.local"
  - name: PYTHON_OPERATOR_BATCH_PROCESSOR_KAFKA_BROKER_URL
    value: "http://python-operator-batch-processor.raga.svc.cluster.local"
  - name: LLM_OPERATOR
    value: "http://llm-operator.raga-models.svc.cluster.local"
  - name: FASTER_RCNN_MODEL_URL
    value: "http://faster-rcnn-model.raga-models.svc.cluster.local/"
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: aws-keys
        key: AWS_ACCESS_KEY_ID
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: aws-keys
        key: AWS_SECRET_ACCESS_KEY