# Default values for testing-platform-backend.
image:
  repository: "ragaai/faster-rcnn-model-release"
  tag: "6-901c8b7"
  pullPolicy: IfNotPresent

imagePullSecrets:
  create: true
  name: "regcred"

fullnameOverride: "faster-rcnn-model"

serviceAccount:
  create: false
  name: "backend"
  annotations: {}

broker:
  create: false
  dlq: "event-failure-capture"
  retry: 1

trigger:
  create: false

service:
  port: 8000

DisablePublicAccess: false

resources:
  limits:
    cpu: 2
    memory: 3000M
  requests:
    cpu: 2
    memory: 3000M

hpa:
  # metric availabe values memory | cpu
  create: true
  metric: memory
  target: 80
  
autoscaling:
  minReplicas: 0
  maxReplicas: 10
  ScaleDownDelay: 2m

livenessProbe:
  httpGet:
    path: /api/healthcheck
    port: 8000
  initialDelaySeconds: 10
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /api/healthcheck
    port: 8000
  initialDelaySeconds: 3
  periodSeconds: 3


containerConcurrency:
  enable: true
  limit: 1

PVC:
  enable: false
  cloud: azure  #allowable values aws | azure
  name: "model-executor-pvc"
  storageClassName: "efs-sc"
  #following values required for only aws efs
  storage: 50Gi
  csiDriver: "efs.csi.aws.com"
  FilesystemID: "fs-0b2eb5c3625e0aed9"

env:
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: faster-rcnn-model
        key: AWS_ACCESS_KEY_ID
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: faster-rcnn-model
        key: AWS_SECRET_ACCESS_KEY