# Default values for testing-platform-backend.
image:
  repository: "ragaai/model-executor-release"
  tag: "14-cd18b27"
  pullPolicy: IfNotPresent

imagePullSecrets:
  create: true
  name: "regcred"

fullnameOverride: "model-executor"

serviceAccount:
  create: false
  name: "raga-role"

broker:
  create: true
  dlq: "event-failure-capture"
  retry: 1

trigger:
  create: true

service:
  port: 8000
  NodePort:
    create: false
    port: 31000

DisablePublicAccess: false

resources:
  limits:
    cpu: 1
    memory: 4096M
  requests:
    cpu: 1
    memory: 4096M

hpa:
  # metric availabe values memory | cpu
  metric: memory
  target: 80
  
autoscaling:
  minReplicas: 0
  maxReplicas: 3
  ScaleDownDelay: 2m

livenessProbe:
  httpGet:
    path: /api/healthcheck
    port: 8000
  initialDelaySeconds: 10
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /api/healthcheck
    port: 8000
  initialDelaySeconds: 3
  periodSeconds: 3


containerConcurrency:
  enable: true
  limit: 1


PVC:
  enable: true
  cloud: azure  #allowable values aws | azure
  name: "model-executor-pvc"
  storageClassName: "azurefile"
  #following values required for only aws efs
  storage: 50Gi
  csiDriver: "efs.csi.aws.com"
  FilesystemID: "fs-0b2eb5c3625e0aed9"