apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "ragaai-helm.fullname" . }}
  name: {{ include "ragaai-helm.fullname" . }}
  namespace: raga-models
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "ragaai-helm.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "ragaai-helm.fullname" . }}
    spec:
      containers:
      - env: {{ .Values.env | toYaml | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: IfNotPresent
        {{- if .Values.serviceAccount.create }}
        serviceAccountName: {{ .Values.serviceAccount.name }}
        {{- end }}
        livenessProbe: {{ .Values.livenessProbe | toYaml | nindent 10 }}
        name: user-container
        ports:
        - containerPort: {{ .Values.service.port }}
          name: user-port
          protocol: TCP
        readinessProbe: {{ .Values.readinessProbe | toYaml | nindent 10 }}
        resources: {{ .Values.resources | toYaml | nindent 10 }}
      imagePullSecrets:
      - name: regcred
