{{- if and .Values.PVC.enable }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.PVC.name }}
spec:
  capacity:
    storage: {{ .Values.PVC.storage }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.PVC.storageClassName }}
{{- end }}