{{- if .Values.domainmapping.create -}}

apiVersion: serving.knative.dev/v1beta1
kind: DomainMapping
metadata:
 name: {{ .Values.domainmapping.domain }}
 namespace: raga
spec:
 ref:
   name: {{ .Values.domainmapping.service }}
   kind: Service
   apiVersion: serving.knative.dev/v1
{{- end }}
---
{{- if .Values.domainmapping.create -}}
apiVersion: networking.internal.knative.dev/v1alpha1
kind: ClusterDomainClaim
metadata:
  name: {{ .Values.domainmapping.domain }}
spec:
  namespace: raga
{{- end }}